"""Summarize text with a local Hugging Face pipeline."""


def summarize(text: str, min_length: int = 5, max_length: int = 40) -> str:
    """Return a deterministic summary generated by BART."""
    from transformers import pipeline

    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
    output = summarizer(
        text,
        max_length=max_length,
        min_length=min_length,
        do_sample=False,
    )
    return str(output[0]["summary_text"])


def main() -> None:
    article = (
        "A university launched a new AI laboratory focused on practical "
        "applications, responsible evaluation, and student research."
    )
    print(summarize(article))


if __name__ == "__main__":
    main()
